#!/bin/python3

from urllib3 import PoolManager
from json import loads
from os import getenv

OAUTH_TOKEN = getenv('SPOTIFY_OAUTH_TOKEN_I3BLOCKS')

http = PoolManager()
r = http.request(
    'GET',
    'https://api.spotify.com/v1/me/player/currently-playing',
    headers={'Authorization': 'Bearer '+OAUTH_TOKEN}
)
j = loads(r.data.decode('UTF-8'))

title = j['item']['name']
artist = j['item']['artists'][0]['name']
print('{} - {}'.format(title, artist))
